version: '3.7'
services: 
    web:
        container_name: "docker_compose_mapperapi"
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - .:/app
        port:
            - "3001:3000"
        environment: 
            - NODE_ENV=development
